CXXFLAGS =       -I/home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software//boost_1_59_0
LDFLAGS =   
LIBS =  -L/home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software//boost_1_59_0/libs -lboost_1_59_0

CLONE_CURRENT_EXCEPTION_NON_INTRUSIVE_DEPS = 

clone_current_exception_non_intrusive_d.o : clone_current_exception_non_intrusive.cpp $(CLONE_CURRENT_EXCEPTION_NON_INTRUSIVE_DEPS)
	@c++ -c -std=c++17 -Wall  -g $(CXXFLAGS) -o clone_current_exception_non_intrusive_d.o clone_current_exception_non_intrusive.cpp

clone_current_exception_non_intrusive.o : clone_current_exception_non_intrusive.cpp $(CLONE_CURRENT_EXCEPTION_NON_INTRUSIVE_DEPS)
	@c++ -c -std=c++17 -Wall  -DNDEBUG -O3 -funroll-loops $(CXXFLAGS) -o clone_current_exception_non_intrusive.o clone_current_exception_non_intrusive.cpp


