CXXFLAGS =       -I/home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software//ITSOL_2/INC
LDFLAGS =   
LIBS =  -L/home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software//ITSOL_2 -litsol

MATOPS_DEPS = 

MatOps.o : MatOps.c $(MATOPS_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o MatOps.o MatOps.c

MatOps_d.o : MatOps.c $(MATOPS_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o MatOps_d.o MatOps.c



PQ_DEPS = 

PQ.o : PQ.c $(PQ_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o PQ.o PQ.c

PQ_d.o : PQ.c $(PQ_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o PQ_d.o PQ.c



ARMS2_DEPS = 

arms2.o : arms2.c $(ARMS2_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o arms2.o arms2.c

arms2_d.o : arms2.c $(ARMS2_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o arms2_d.o arms2.c



AUXILL_DEPS = 

auxill.o : auxill.c $(AUXILL_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o auxill.o auxill.c

auxill_d.o : auxill.c $(AUXILL_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o auxill_d.o auxill.c



FGMR_DEPS = 

fgmr.o : fgmr.c $(FGMR_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o fgmr.o fgmr.c

fgmr_d.o : fgmr.c $(FGMR_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o fgmr_d.o fgmr.c



ILUK_DEPS = 

iluk.o : iluk.c $(ILUK_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o iluk.o iluk.c

iluk_d.o : iluk.c $(ILUK_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o iluk_d.o iluk.c



ILUT_DEPS = 

ilut.o : ilut.c $(ILUT_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o ilut.o ilut.c

ilut_d.o : ilut.c $(ILUT_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o ilut_d.o ilut.c



ILUTC_DEPS = 

ilutc.o : ilutc.c $(ILUTC_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o ilutc.o ilutc.c

ilutc_d.o : ilutc.c $(ILUTC_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o ilutc_d.o ilutc.c



ILUTPC_DEPS = 

ilutpC.o : ilutpC.c $(ILUTPC_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o ilutpC.o ilutpC.c

ilutpC_d.o : ilutpC.c $(ILUTPC_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o ilutpC_d.o ilutpC.c



INDSETC_DEPS = 

indsetC.o : indsetC.c $(INDSETC_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o indsetC.o indsetC.c

indsetC_d.o : indsetC.c $(INDSETC_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o indsetC_d.o indsetC.c



MISC_DEPS = 

misc.o : misc.c $(MISC_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o misc.o misc.c

misc_d.o : misc.c $(MISC_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o misc_d.o misc.c



PILUNEW_DEPS = 

piluNEW.o : piluNEW.c $(PILUNEW_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o piluNEW.o piluNEW.c

piluNEW_d.o : piluNEW.c $(PILUNEW_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o piluNEW_d.o piluNEW.c



SETBLKS_DEPS = 

setblks.o : setblks.c $(SETBLKS_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o setblks.o setblks.c

setblks_d.o : setblks.c $(SETBLKS_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o setblks_d.o setblks.c



SETS_DEPS = 

sets.o : sets.c $(SETS_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o sets.o sets.c

sets_d.o : sets.c $(SETS_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o sets_d.o sets.c



SVDINVC_DEPS = 

svdInvC.o : svdInvC.c $(SVDINVC_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o svdInvC.o svdInvC.c

svdInvC_d.o : svdInvC.c $(SVDINVC_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o svdInvC_d.o svdInvC.c



SYSTIMER_DEPS = 

systimer.o : systimer.c $(SYSTIMER_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o systimer.o systimer.c

systimer_d.o : systimer.c $(SYSTIMER_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o systimer_d.o systimer.c



TOOLS_DEPS = 

tools.o : tools.f $(TOOLS_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o tools.o tools.f

tools_d.o : tools.f $(TOOLS_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o tools_d.o tools.f



VBILUK_DEPS = 

vbiluk.o : vbiluk.c $(VBILUK_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o vbiluk.o vbiluk.c

vbiluk_d.o : vbiluk.c $(VBILUK_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o vbiluk_d.o vbiluk.c



VBILUT_DEPS = 

vbilut.o : vbilut.c $(VBILUT_DEPS)
	@gcc -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o vbilut.o vbilut.c

vbilut_d.o : vbilut.c $(VBILUT_DEPS)
	@gcc -c -Wall  -g $(CXXFLAGS) -o vbilut_d.o vbilut.c


