CXXFLAGS =    
LDFLAGS =  
LIBS = 

all:
	@ar -r libarpack_bindings_d.a   /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/dneupd_c_d.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/dseupd_c_d.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/sneupd_c_d.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/sseupd_c_d.o
	ar -r libarpack_bindings.a   /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/dneupd_c.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/dseupd_c.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/sneupd_c.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/arpack_bindings/lib/src/sseupd_c.o
