CXXFLAGS =    
LDFLAGS =  
LIBS = 

all:
	@ar -r libitsol_pp_d.a   /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/arms_d.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/iluk_d.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/ilut_d.o
	ar -r libitsol_pp.a   /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/arms.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/iluk.o /home/simond/hlibpro-3.0-Ubuntu22.04/hlibpro-3.0/numerics_software/itsol++/lib/src/ilut.o
