CXXFLAGS =    
LDFLAGS =  
LIBS = 

DNEUPD_C_DEPS = 

dneupd_c.o : dneupd_c.f $(DNEUPD_C_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o dneupd_c.o dneupd_c.f

dneupd_c_d.o : dneupd_c.f $(DNEUPD_C_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o dneupd_c_d.o dneupd_c.f



DSEUPD_C_DEPS = 

dseupd_c.o : dseupd_c.f $(DSEUPD_C_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o dseupd_c.o dseupd_c.f

dseupd_c_d.o : dseupd_c.f $(DSEUPD_C_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o dseupd_c_d.o dseupd_c.f



SNEUPD_C_DEPS = 

sneupd_c.o : sneupd_c.f $(SNEUPD_C_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o sneupd_c.o sneupd_c.f

sneupd_c_d.o : sneupd_c.f $(SNEUPD_C_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o sneupd_c_d.o sneupd_c.f



SSEUPD_C_DEPS = 

sseupd_c.o : sseupd_c.f $(SSEUPD_C_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o sseupd_c.o sseupd_c.f

sseupd_c_d.o : sseupd_c.f $(SSEUPD_C_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o sseupd_c_d.o sseupd_c.f


