CXXFLAGS =    
LDFLAGS =  
LIBS = 

CMOUT_DEPS = 

cmout.o : cmout.f $(CMOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o cmout.o cmout.f

cmout_d.o : cmout.f $(CMOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o cmout_d.o cmout.f



CVOUT_DEPS = 

cvout.o : cvout.f $(CVOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o cvout.o cvout.f

cvout_d.o : cvout.f $(CVOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o cvout_d.o cvout.f



DMOUT_DEPS = 

dmout.o : dmout.f $(DMOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o dmout.o dmout.f

dmout_d.o : dmout.f $(DMOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o dmout_d.o dmout.f



DVOUT_DEPS = 

dvout.o : dvout.f $(DVOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o dvout.o dvout.f

dvout_d.o : dvout.f $(DVOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o dvout_d.o dvout.f



ICNTEQ_DEPS = 

icnteq.o : icnteq.f $(ICNTEQ_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o icnteq.o icnteq.f

icnteq_d.o : icnteq.f $(ICNTEQ_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o icnteq_d.o icnteq.f



ICOPY_DEPS = 

icopy.o : icopy.f $(ICOPY_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o icopy.o icopy.f

icopy_d.o : icopy.f $(ICOPY_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o icopy_d.o icopy.f



ISET_DEPS = 

iset.o : iset.f $(ISET_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o iset.o iset.f

iset_d.o : iset.f $(ISET_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o iset_d.o iset.f



ISWAP_DEPS = 

iswap.o : iswap.f $(ISWAP_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o iswap.o iswap.f

iswap_d.o : iswap.f $(ISWAP_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o iswap_d.o iswap.f



IVOUT_DEPS = 

ivout.o : ivout.f $(IVOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o ivout.o ivout.f

ivout_d.o : ivout.f $(IVOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o ivout_d.o ivout.f



SECOND_DEPS = 

second.o : second.f $(SECOND_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o second.o second.f

second_d.o : second.f $(SECOND_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o second_d.o second.f



SMOUT_DEPS = 

smout.o : smout.f $(SMOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o smout.o smout.f

smout_d.o : smout.f $(SMOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o smout_d.o smout.f



SVOUT_DEPS = 

svout.o : svout.f $(SVOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o svout.o svout.f

svout_d.o : svout.f $(SVOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o svout_d.o svout.f



ZMOUT_DEPS = 

zmout.o : zmout.f $(ZMOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o zmout.o zmout.f

zmout_d.o : zmout.f $(ZMOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o zmout_d.o zmout.f



ZVOUT_DEPS = 

zvout.o : zvout.f $(ZVOUT_DEPS)
	@gfortran -c -Wall  -O3 -funroll-loops $(CXXFLAGS) -o zvout.o zvout.f

zvout_d.o : zvout.f $(ZVOUT_DEPS)
	@gfortran -c -Wall  -g $(CXXFLAGS) -o zvout_d.o zvout.f


